name:                ImageCompressor
version:             0.1.0.0
github:              "guillaumebgd/ImageCompressor"
license:             BSD3
author:              "Guillaume Bogard-Coquard"
maintainer:          "guillaume.bogardcoquard@gmail.com"
copyright:           "2022 Guillaume Bogard-Coquard"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/guillaumebgd/ImageCompressor/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - random

executables:
  ImageCompressor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImageCompressor
    - random

tests:
  ImageCompressor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImageCompressor
    - hspec
    - random
